### ISSUE TITLE
Getting more done in GitHub with ZenHub

### ISSUE THREAD

**Issue by beniza** [tfbf/punjabi_bible_1945#1]
Hola! @beniza has created a [ZenHub](http://www.zenhub.com) account for the **tfbf** organization. ZenHub is the only project management tool integrated natively in GitHub – created specifically for fast-moving, software-driven teams.

----

#### How do I use ZenHub?

To get set up with ZenHub, all you have to do is **[download the browser extension](https://www.zenhub.com?utm_source=ZHOnboarding)** and log in with your GitHub account. Once you do, you’ll get access to ZenHub’s complete feature-set immediately.

#### What can ZenHub do?

ZenHub adds a series of enhancements directly inside the GitHub UI:

- Real-time, customizable task boards for GitHub issues;
- Multi-Repository burndown charts, estimates, and velocity tracking based on GitHub Milestones;
- Personal to-do lists and task prioritization;
- Time-saving shortcuts – like a quick repo switcher, a “Move issue” button, and much more.

### [Add ZenHub to GitHub](https://www.zenhub.com?utm_source=ZHOnboarding)

_Still curious? See [more ZenHub features](https://www.zenhub.com/features?utm_source=ZHOnboarding) or read [user reviews](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews). This issue was written by your friendly ZenHub bot, posted by request from @beniza._

![ZenHub Board](https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png)

**Comment by DavidHaslam** [comment]
In Firefox, the ZenHub add-on is not yet compatible with multiprocess.

**Comment by DavidHaslam** [comment]
A local friend advised me thus:

One tip if you ever start working on other people's repos: after forking, ALWAYS create A DIFFERENT BRANCH and work on that one. *Never* merge your changes to master; if you want to track the original repo, create a new remote and point master to it, then periodically merge FROM master TO your branch if necessary. If you want to send a patch, again create a new branch from master, make changes (merging them from other existing branches if necessary), then send the pull request and stop working on that branch; if/once the pull is accepted, delete the branch and update master. Took me a while to get my head around that, but it's pretty much the standard process, otherwise pull requests get polluted with unrelated commits and will be rejected or ignored.

**Comment by DavidHaslam** [comment]
Those of you that have an iOS device may find this app useful. I like using it.

[CodeHub](http://codehub-app.com/) is the most complete, unofficial, client for GitHub on the iOS platform.

**Comment by DavidHaslam** [comment]
You may also like to consider this iOS app too.

[Git2Go](http://git2go.com/) is the first app for iOS which unleashes your full development productivity from everywhere. Clone all your GitHub and Bitbucket repositories with just one tap, manage branches and easily commit changes after you’ve edited code on-the-fly - All from your iPhone and iPad!

**Comment by DavidHaslam** [comment]
As this issue was created merely to exchange information, maybe it's time to close it now?

**Comment by DavidHaslam** [comment]
Let's close this now @beniza
