### ISSUE TITLE
Add parallel passage references using USFM marker \r

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#75]
I think these are available in the printed version of the 1945 Edition.

cf. These do exist in the online [Punjabi Bible](http://punjabivirsa.co.in/en/Punjabi_Bible)

These should be added to the USFM files using the **\r** tag.

Book abbreviations should match those in **\toc3**

For the SWORD module, a Punjabi [locale file](https://crosswire.org/wiki/DevTools:Locale_Files) will be required.

**Comment by joshykurian** [comment]
The online bible is 2016 Revised Version and the work is based on 1945
scanned copy which is currently in Public Domain. The Section headings
(/s), References (/r) and Introduction (/ip) are not present in 1945
version, but added in revised version in 2016.
On 10-Jan-2017 10:57 PM, "David Frank Haslam" <notifications@github.com>
wrote:

I think these are available in the printed version of the 1945 Edition.

cf. These do exist in the online Punjabi Bible
<http://punjabivirsa.co.in/en/Punjabi_Bible>

These should be added to the USFM files using the *\r* tag.

Book abbreviations should match those in *\toc3*

For the SWORD module, a Punjabi locale file
<https://crosswire.org/wiki/DevTools:Locale_Files> will be required.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tfbf/punjabi_bible_1945/issues/75>, or mute the thread

**Comment by DavidHaslam** [comment]
Thanks for clarification.
